// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovdtbqlterfmfyeovlcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92ZHRicWx0ZXJmbWZ5ZW92bGNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNTM5MzksImV4cCI6MjA2MzYyOTkzOX0.gQgNQGKAcW6h9XybA8OkEeddFpfcJUI2gUgTWyajlvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);